name: Build Images

on:
  push:
    branches:
      - master

jobs:
  images:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build amd64
        run: docker build your-username/postcodes-node:latest:manifest-amd64 --build-arg ARCH=amd64/ -f ./Dockerfile
        run: docker push your-username/postcodes-node:latest:manifest-amd64

      - name: build arm64v8
        run: docker build your-username/postcodes-node:latest:manifest-arm64v8 --build-arg ARCH=arm64v8/ -f ./Dockerfile
        run: docker push your-username/postcodes-node:latest:manifest-arm64v8

      #- name: build pg amd64
      #  run: docker build your-username/postcodes-pg:latest:manifest-amd64 --build-arg ARCH=amd64/ -f ./Dockerfile.pg
      #  run: docker push your-username/postcodes-pg:latest:manifest-amd64

      #- name: build pg arm64v8
      #  run: docker build your-username/postcodes-pg:latest:manifest-arm64v8 --build-arg ARCH=arm64v8/ -f ./Dockerfile.pg
      #  run: docker push your-username/postcodes-pg:latest:manifest-arm64v8

      - name: manifest
        run: docker manifest create your-username/postcodesio:manifest-latest
        with:
          amend: your-username/postcodes-node:latest:manifest-amd64
          amend: your-username/postcodes-node:latest:manifest-arm64v8
          #amend: your-username/postcodes-pg:latest:manifest-amd64
          #amend: your-username/postcodes-pg:latest:manifest-arm64v8
        run: docker manifest push your-username/postcodesio:manifest-latest